# Generated by Django 5.1.3 on 2025-12-11 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, max_length=250, unique=True)),
                (
                    "overview",
                    models.TextField(
                        help_text="A high-level description for the dashboard."
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="The sequence number for the dashboard.", unique=True
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True for the first two modules.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Module",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="student_igcse.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(editable=False, max_length=250)),
                ("short_description", models.CharField(max_length=500)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="The sequence of the topic within the module."
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        help_text="The module this topic belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="student_igcse.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic / Lesson",
                "ordering": ["module", "order"],
                "unique_together": {("module", "slug")},
            },
        ),
        migrations.CreateModel(
            name="FlashcardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets",
                        to="student_igcse.module",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_sets",
                        to="student_igcse.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Key Definitions' or 'Gas Laws Simulator'",
                        max_length=200,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("notes", "Student Notes (Rich Text)"),
                            ("interactive", "Interactive HTML/JS/CSS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content_data",
                    models.TextField(
                        help_text="The raw content: notes (rich text) or the full interactive HTML/JS/CSS."
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        help_text="The order of the content item on the topic page."
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="The topic this content belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="student_igcse.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topic Content Item",
                "ordering": ["topic", "order"],
            },
        ),
    ]
