# Generated by Django 5.1.3 on 2025-12-11 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_igcse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
