# Generated by Django 5.1.3 on 2025-12-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_igcse", "0002_alter_module_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="slug",
            field=models.SlugField(max_length=250),
        ),
    ]
