# Generated by Django 5.1.3 on 2025-12-01 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("short_description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_free", models.BooleanField(default=False)),
                ("learning_objectives", models.TextField(blank=True)),
                ("syllabus_snapshot", models.TextField(blank=True)),
                ("spark_question", models.TextField(blank=True)),
                ("teacher_presentation", models.TextField(blank=True)),
                ("personalisation_secure", models.TextField(blank=True)),
                ("personalisation_foundation", models.TextField(blank=True)),
                ("personalisation_support", models.TextField(blank=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="cam_igcse.module",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="learning_materials/")),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("lesson_plan", "Lesson Plan"),
                            ("teaching_strategy", "Teaching Strategy"),
                            ("student_task", "Student Task"),
                            ("personalisation_support", "Personalisation Support"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="cam_igcse.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("collaborative", "Collaborative"),
                            ("solo", "Solo"),
                            ("reflection", "Reflection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="cam_igcse.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
