# Generated by Django 5.1.3 on 2025-11-22 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dawapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediafile",
            options={"ordering": ["-uploaded"]},
        ),
        migrations.AddField(
            model_name="mediafile",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
