# Generated by Django 5.1.3 on 2025-11-22 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dawapp", "0002_alter_mediafile_options_mediafile_duration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediafile",
            options={},
        ),
        migrations.RemoveField(
            model_name="mediafile",
            name="duration",
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
